FROM rocker/r-base:4.3.2

# Install required R packages
RUN R -e "install.packages(c('ggplot2', 'gridExtra', 'grid'), repos='https://cloud.r-project.org')"

# Set working directory
WORKDIR /app

# Copy the R analysis script
COPY fasta_analysis.R /app/fasta_analysis.R

# Copy CSV data (generated by Python analysis)
COPY results/*.csv /app/data/

# Create output directory
RUN mkdir -p /app/output /app/results

# Set environment for non-interactive R
ENV R_BATCH=true

# Default command - analyze ATG motif
CMD ["Rscript", "fasta_analysis.R", "data/motif_analysis_ATG.csv", "results", "ATG"]
